[workspace]
members = [
  "libs/dex-primitives",
  "libs/dex-math",
  "libs/dex-messaging",
  "services/indexer",
  "services/quoter",
  "services/api-gateway",
  "services/order-service",
  "services/user-service",
  "services/matching-engine",
  "services/wallet-service",
  "services/notification-service",
  "services/admin-service",
  "clients/web",
]
resolver = "2"

[profile.dev]
opt-level       = 0
incremental     = true
codegen-units   = 256
debug           = 1
lto             = false
panic           = "abort"
overflow-checks = false
strip           = "debuginfo"

[profile.dev.package."*"]
opt-level = 3
debug = false

[profile.dev.build-override]
opt-level = 3

[profile.release]
opt-level       = 3
incremental     = true
codegen-units   = 16
lto             = "thin"
strip           = "symbols"

[profile.release.package."*"]
opt-level     = 1
codegen-units = 256

[profile.release-dev]
inherits = "release"
opt-level = 2
debug = true
lto = false
codegen-units = 32