version: '3.8'

services:
  # Message Queue (using Redis Streams for simplicity)
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  # Database (using PostgreSQL for simplicity)
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: rxdex
      POSTGRES_USER: rxdex
      POSTGRES_PASSWORD: rxdex123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # API Gateway
  api-gateway:
    image: nginx:latest  # Using nginx as a placeholder
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

  # Quoter Service
  quoter:
    image: nginx:latest  # Using nginx as a placeholder
    ports:
      - "8081:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

  # Order Service
  order-service:
    image: nginx:latest  # Using nginx as a placeholder
    ports:
      - "8083:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

  # User Service
  user-service:
    image: nginx:latest  # Using nginx as a placeholder
    ports:
      - "8084:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

  # Matching Engine
  matching-engine:
    image: nginx:latest  # Using nginx as a placeholder
    ports:
      - "8085:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

  # Wallet Service
  wallet-service:
    image: nginx:latest  # Using nginx as a placeholder
    ports:
      - "8086:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

  # Notification Service
  notification-service:
    image: nginx:latest  # Using nginx as a placeholder
    ports:
      - "8087:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

  # Web Frontend
  web:
    image: caddy:2-alpine
    ports:
      - "8082:8082"
    volumes:
      - ./clients/web/Caddyfile:/etc/caddy/Caddyfile
      - ./clients/web/dist:/usr/share/caddy
    depends_on:
      - api-gateway

volumes:
  redis_data:
  postgres_data: