version: '3.8'

services:
  # Message Queue (using Redis Streams for simplicity)
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  # Database (using PostgreSQL for simplicity)
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: rxdex
      POSTGRES_USER: rxdex
      POSTGRES_PASSWORD: rxdex123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # API Gateway
  api-gateway:
    build: 
      context: .
      dockerfile: services/api-gateway/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - QUOTER_URL=http://quoter:8081
      - USER_SERVICE_URL=http://user-service:8084
      - ORDER_SERVICE_URL=http://order-service:8083
      - ADMIN_SERVICE_URL=http://admin-service:8088
      - TRADING_SERVICE_URL=http://trading-service:8089
    depends_on:
      - quoter
      - user-service
      - order-service
      - admin-service
      - trading-service

  # Quoter Service
  quoter:
    build:
      context: .
      dockerfile: services/quoter/Dockerfile
    ports:
      - "8081:8081"

  # Order Service
  order-service:
    build:
      context: .
      dockerfile: services/order-service/Dockerfile
    ports:
      - "8083:8083"
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis

  # User Service
  user-service:
    build:
      context: .
      dockerfile: services/user-service/Dockerfile
    ports:
      - "8084:8084"
    environment:
      - DATABASE_URL=postgresql://rxdex:rxdex123@postgres:5432/rxdex
      - REDIS_URL=redis://redis:6379
    depends_on:
      - postgres
      - redis

  # Matching Engine
  matching-engine:
    build:
      context: .
      dockerfile: services/matching-engine/Dockerfile
    ports:
      - "8085:8085"
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis

  # Wallet Service
  wallet-service:
    build:
      context: .
      dockerfile: services/wallet-service/Dockerfile
    ports:
      - "8086:8086"
    environment:
      - DATABASE_URL=postgresql://rxdex:rxdex123@postgres:5432/rxdex
      - REDIS_URL=redis://redis:6379
    depends_on:
      - postgres
      - redis

  # Notification Service
  notification-service:
    build:
      context: .
      dockerfile: services/notification-service/Dockerfile
    ports:
      - "8087:8087"
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis

  # Admin Service
  admin-service:
    build:
      context: .
      dockerfile: services/admin-service/Dockerfile
    ports:
      - "8088:8088"

  # Trading Service
  trading-service:
    build:
      context: .
      dockerfile: services/trading-service/Dockerfile
    ports:
      - "8089:8089"

  # Indexer Service
  indexer:
    build:
      context: .
      dockerfile: services/indexer/Dockerfile
    ports:
      - "8090:8082"

  # Web Frontend
  web:
    build:
      context: ./clients/web
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - api-gateway

volumes:
  redis_data:
  postgres_data: