apiVersion: apps/v1
kind: Deployment
metadata:
  name: quoter
spec:
  replicas: 3
  selector:
    matchLabels:
      app: quoter
  template:
    metadata:
      labels:
        app: quoter
    spec:
      containers:
      - name: quoter
        image: rxdex/quoter:latest
        ports:
        - containerPort: 8081
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: quoter
spec:
  selector:
    app: quoter
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081