name: Deploy Documentation

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: 1.78
        override: true

    - name: Generate documentation
      run: |
        cargo doc --no-deps
        echo '<!DOCTYPE html><html><head><meta http-equiv="refresh" content="0; url=rx_dex/index.html"></head><body></body></html>' > target/doc/index.html

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./target/doc